### ISSUE TITLE
Partitions on Tas v12

### ISSUE THREAD

**Issue by stain3565** [JamesSwift/localbytes-plug-pm#11]
I have a new Tasmota plug v12.2.0

I want to flash with Esphome instead so am looking at using your project. However, to ensure I don't just end up "bricking" my plug, I need to ask a question raised by a contributor to the HA forum. 

> But tasmota starting v12 has different partition system that’s not compatible for esphome ota (indicated by safeboot partition in the settings).
> 
> There’s a workaround for that [Read/Write bootloader, partition table and any partition via OTA by angelnu · Pull Request #5535 · esphome/esphome · GitHub](https://github.com/esphome/esphome/pull/5535)
> 

Is this likely to be an issue if installing your project onto a newer plug?

**Comment by angelnu** [comment]
Until my PR is merged, you will need to compile esphome out of the PR branch. You will also need to use the command line to update the partition table. Just follow the instructions in the PR and it should work.

The PR is still experimental, thought, so if you have the chance to test on a device that does not require destroying to program via serial would be safer. I used a Shelly Plus 1PM Mini to test.

The upload-factory-ota does a backup of the partition table from Tasmota so it can flash it back if something goes wrong.

**Comment by JamesSwift** [comment]
Thanks for the information. I don't have a newer plug to test this on, so proceed with caution.
