### ISSUE TITLE
Plug gets warm

### ISSUE THREAD

**Issue by PaulOckenden** [JamesSwift/localbytes-plug-pm#12]
I notice that when flashed with ESPHome the plug gets warm (not hot). I wondered whether there's any way to optimise that away a bit, even if it's at the expense of the monitoring being slightly less responsive?

**Comment by JamesSwift** [comment]
Hi. Yes I've noticed that too on some of my plugs. I've raised it with Adam who runs localbytes, and we never got to the bottom of it. I've tried various methods to reduce the power draw such as lowering the default WiFi broadcast strength. That helped a bit, but didn't really solve the problem or explain it. If you find out anything, feel free to update this issue. Sorry I can't give you a better answer.
