### ISSUE TITLE
Even with 1.6.3 disable LED doesn’t persist.

### ISSUE THREAD

**Issue by PaulOckenden** [JamesSwift/localbytes-plug-pm#13]
As the title says - disable LED doesn’t survive a power cut. 

Plugs bought pre-flashed with 1.6.1 last week, then upgraded to 1.6.3 via web interface. HA reports 1.6.3 correctly.

**Comment by PaulOckenden** [comment]
I should point out that this is observed whether I do a disable LED in HA, or via the plug’s web interface. Same in both cases.

**Comment by JamesSwift** [comment]
Interesting. I've not been able to replicate that behaviour. How long are you waiting after disabling the led before cutting power? ESPHome batches up changes to write to flash to cut down on the wear. So the change won't be saved immediately, normally within a minute or less. If you open the logs in ESPHome you can observe when the changes are written to flash to verify before cutting power for the purposes of debugging.
