### ISSUE TITLE
output cycling when rebuilding firmware

### ISSUE THREAD

**Issue by opb** [JamesSwift/localbytes-plug-pm#15]
Hi

I find that when rebuilding and uploading the firmware in ESPHome, it will turn off the output. Is this a software or hardware issue? ie, is it physically impossible given the hardware to *not* power cycle when reloading firmware?

Thanks

**Comment by JamesSwift** [comment]
Hmm. I'm not sure. You could try changing `default_state: "RESTORE_DEFAULT_OFF"` to `default_state: "RESTORE_DEFAULT_ON"` and see if it makes a difference. If the relay itself is Normally Open, it might be impossible to maintain power to it during a power cycle, depending on how esphome initialises.

**Comment by kgleeson** [comment]
I set `default_state: "ALWAYS_ON"` on my devices that I don't want power cycling after an update and I haven't had an issue

**Comment by opb** [comment]
Thanks for the responses. I did set `default_state: ALWAYS_ON` in the `substitutions` but it still very briefly flicks the power on and off when rebooting or during the reboot part of an upgrade - you can hear the audible click of the relay and attached lamp (for testing) flicks off them back on. It’s quick, but will drop the load of a power supply.

should I be configuring `ALWAYS_ON` elsewhere, or am I going to have to accept that this won’t do what I want?

cheers!

**Comment by JamesSwift** [comment]
Ah, I'm not really sure what else to suggest. I wonder if the tasmota firmware does it too? I suspect it will depend on how it's wired to the output pin of the esp8266. When the chip reboots, the pin might default to high or low before the firmware takes over and sets it.

**Comment by nijel** [comment]
https://github.com/LocalBytes/esphome-localbytes-plug/pull/6 has the fix for this.

**Comment by opb** [comment]
THanks @nijel - I can confirm this has worked for me.

**Comment by JamesSwift** [comment]
Thanks! I didn't know about that feature of esphome. I've updated the main branch.
