### ISSUE TITLE
ESPHOME 2024.6 changes to OTA

### ISSUE THREAD

**Issue by summongod** [JamesSwift/localbytes-plug-pm#16]
https://esphome.io/changelog/2024.6.0#ota-platforms
OTA Platforms
With the above mentioned http_request OTA platform, we made the decision to split out the current ota server to its own platform to make the code more managable and to allow for more flexibility going forward.

Because of this, all configurations that currently have ota: in them will fail to validate after updating to this release.

You will need to change the configuration by adding a new line as below:

# Old
ota:

ota:
  password: "xxxx"

# New
ota:
  platform: esphome

ota:
  platform: esphome
  password: "xxxx"
As part of this change also, [safe_mode](https://esphome.io/components/safe_mode) has been pulled out into its own top level component. It is automatically included in any configuration that has an ota configuration block, so there is nothing you need to do unless you were overriding some of the safe mode specific configurations.

**Comment by liambresnahan** [comment]
Could we get this merged please @JamesSwift ?

**Comment by liambresnahan** [comment]
Thanks!!
