### ISSUE TITLE
Variable/Subs for Button and LED default states

### ISSUE THREAD

**Issue by edwardpoll** [JamesSwift/localbytes-plug-pm#18]
Hi James, 

Not an issue as such but wanted to reach out, would it be possible for you to add variables for the default button and led states so we can sub them in and out as we do for the default power state.

Not a massive change and would help enormously with my automation states without having to fork away from your maintained code.

Cheers!

**Comment by JamesSwift** [comment]
Hi @edwardpoll. That's a good idea. I don't actually have any of these plugs in use anymore though - I gave them to my nephew - so I'm not able to test any changes I make to the repo. If you want to test the change on your end and submit a pull request I'll happily merge it. Although you might want to switch to the https://github.com/LocalBytes/esphome-localbytes-plug LocalBytes maintained version now, and submit your pull request there.

**Comment by JamesSwift** [comment]
Hi @edwardpoll. I recently bought a few more of these plugs after moving house, so I've been catching up on the repo. I've implemented your idea in a new release: https://github.com/JamesSwift/localbytes-plug-pm/releases/tag/v1.8.0

**Comment by micsco** [comment]
Thanks James!
