### ISSUE TITLE
issues with flashing minimal.bin

### ISSUE THREAD

**Issue by Safety-Th1rd** [JamesSwift/localbytes-plug-pm#2]
I'm very new to Github so not sure how to suggest an addition to the documentation so hope this is correct. 

I found when trying to flash the localbytes plug with the minimal.bin file that it would always say the file was too big. Tried gzipping it but same issue.

After lots of research, I found that if you do an OTA upgrade to the minimal bin file using the following address http://ota.tasmota.com/tasmota/release/tasmota-minimal.bin.gz it would work perfectly. I could then upgrade using James's downloaded localbytes bin file with no issue.

Just thought that might be worth adding to the documentation to help others who might find the same issue.

**Comment by JamesSwift** [comment]
@Safety-Th1rd Thanks for the information. I'll add it to the readme.
