### ISSUE TITLE
 ESPHome 2023.7.0 causes and error when updating this

### ISSUE THREAD

**Issue by markleman** [JamesSwift/localbytes-plug-pm#7]
Having updated to ESPhome 2023.7.0 I get the following error when trying to update my plugs:

"The restore_state option has been removed in 2023.7.0. Use the restore_mode option instead."

Thanks for your time and effort in maintaining this.

**Comment by finalbillybong** [comment]
A pull request has been set up to fix this. Just needs the dev to approve it.

**Comment by drumstick77** [comment]
Hi, I'm unable to update localbytes plug, it's complaining about this
"The restore_state option has been removed in 2023.7.0. Use the restore_mode option instead."

Cheers
